# Generated by Django 3.2.3 on 2021-05-18 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import knowledge.models
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='NA')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.comment_seed')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('contenu', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.industry')),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('contenu', models.TextField(default='NA')),
                ('image', models.ImageField(upload_to='sdgs/')),
            ],
        ),
        migrations.CreateModel(
            name='SDG_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.sdg')),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_seed', models.ImageField(default='Null', upload_to=knowledge.models.profile_seed_directory_path)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField(default='NA', max_length=100)),
                ('pros', models.TextField(default='NA')),
                ('cons', models.TextField(default='NA')),
                ('contenu', models.TextField(default='NA')),
                ('use_case', models.TextField(default='NA')),
                ('aim_seed', models.CharField(choices=[('1', 'To raise awarness'), ('2', 'To share a product or service'), ('3', 'To search for improvement'), ('4', 'To present theoretical results '), ('5', 'To make laugh'), ('6', 'Others')], max_length=30)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ManyToManyField(through='knowledge.Industry_Seed', to='knowledge.Industry')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('sdg', models.ManyToManyField(through='knowledge.SDG_Seed', to='knowledge.SDG')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Value_chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('contenu', models.TextField(default='NA')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.value_chain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(default='NA', max_length=444)),
                ('aim_vision', models.CharField(choices=[('1', 'To raise awarness'), ('2', 'To share a product or service'), ('3', 'To search for improvement'), ('4', 'To present theoretical results '), ('5', 'To make laugh'), ('6', 'Others')], max_length=30)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Value_Chain_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed')),
                ('value_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.value_chain')),
            ],
        ),
        migrations.AddField(
            model_name='seed',
            name='value_chain',
            field=models.ManyToManyField(through='knowledge.Value_Chain_Seed', to='knowledge.Value_chain'),
        ),
        migrations.AddField(
            model_name='sdg_seed',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed'),
        ),
        migrations.CreateModel(
            name='Liked_Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vision_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.vision')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed')),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.comment_seed')),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='industry_seed',
            name='seed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed'),
        ),
        migrations.CreateModel(
            name='Favourites_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed')),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(default='Null', upload_to=knowledge.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed')),
            ],
        ),
        migrations.CreateModel(
            name='Disliked_Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vision_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.vision')),
            ],
        ),
        migrations.CreateModel(
            name='Disliked_Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('seed_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.seed')),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disliked_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge.comment_seed')),
                ('user_related', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='NA')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dislikes_comment_vision', models.ManyToManyField(blank=True, default=None, related_name='dislikes_comment_vision', to=settings.AUTH_USER_MODEL)),
                ('likes_comment_vision', models.ManyToManyField(blank=True, default=None, related_name='likes_comment_vision', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.comment_vision')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vision_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='knowledge.vision')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.AddField(
            model_name='comment_seed',
            name='seed_connected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='knowledge.seed'),
        ),
        migrations.AddField(
            model_name='comment_seed',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
