# Generated by Django 3.2.3 on 2021-05-18 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value_chain_user',
            name='value_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.value_chain'),
        ),
        migrations.AddField(
            model_name='sdg_user',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.sdg'),
        ),
        migrations.AddField(
            model_name='sdg_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='capabilities',
            field=models.ManyToManyField(through='accounts.Capabilities_User', to='accounts.Capabilities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ManyToManyField(through='accounts.Country_User', to='accounts.Country'),
        ),
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.ManyToManyField(through='accounts.Industry_User', to='knowledge.Industry'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sdg',
            field=models.ManyToManyField(through='accounts.SDG_User', to='knowledge.SDG'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='value_chain',
            field=models.ManyToManyField(through='accounts.Value_Chain_User', to='knowledge.Value_chain'),
        ),
        migrations.AddField(
            model_name='liked_feedback',
            name='feedback_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.feedback'),
        ),
        migrations.AddField(
            model_name='liked_feedback',
            name='user_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='industry_user',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.industry'),
        ),
        migrations.AddField(
            model_name='industry_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='follower',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disliked_feedback',
            name='feedback_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.feedback'),
        ),
        migrations.AddField(
            model_name='disliked_feedback',
            name='user_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country_user',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='country_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='capabilities_user',
            name='capabilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.capabilities'),
        ),
        migrations.AddField(
            model_name='capabilities_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
